apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics
        image: nadeeshadulanjanee/analytics-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"  # Increased
          limits:
            cpu: "500m"
            memory: "512Mi"  # Increased
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10  # Reduced
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3   # Faster startup
          periodSeconds: 5
