apiVersion: apps/v1
kind: Deployment
metadata:
  name: lugx-frontend-green
spec:
  replicas: 2
  selector:
    matchLabels: { app: lugx-frontend, color: green }
  template:
    metadata:
      labels: { app: lugx-frontend, color: green }
    spec:
      containers:
      - name: frontend
        image: nadeeshadulanjanee/iit-nginx-static:71bdd6a4c57c8e95a6e7fb5dcc7b76bcddf52988
        ports: [{ containerPort: 80 }]
