apiVersion: apps/v1
kind: Deployment
metadata:
  name: lugx-frontend-blue
  labels:
    app: lugx-frontend
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lugx-frontend
      color: blue
  template:
    metadata:
      labels:
        app: lugx-frontend
        color: blue
    spec:
      containers:
      - name: frontend
        image: ${{ secrets.DOCKER_USERNAME }}/lugx-frontend:${{ github.sha }}
        ports:
        - containerPort: 80
