apiVersion: v1
kind: Service
metadata:
  name: lugx-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: lugx-frontend
    color: blue  # Starts with blue as active
