apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
        - name: game-service
          image: nadeeshadulanjanee/game-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              value: "nadeesha"
            - name: DB_PASSWORD
              value: "secret123"
            - name: DB_NAME
              value: "ordersdb"
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  selector:
    app: game-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
